### PR TITLE
Added BAMO

### PR DESCRIPTION
**Pull request by tmudway**

### CODE REVIEW

**Comment by JannisX11** [comment]
I reviewed your submission. Two notes:
* Blockbench already comes with JSZip by default, so you should treat it as an external dependency.
* Please include the files that are necessary to reproduce the build, such as webpack config and package.json, in the source folder.

**Comment by tmudway** [comment]
> 

Both changes made. Anything else that looks off?

**Comment by SirJain0** [comment]
@tmudway Any news on how this is going? Just curious since this seems like a cool plugin

**Comment by tmudway** [comment]
Updated with requested changes

**Comment by JannisX11** [comment]
Sorry this has been in the queue for so long!

**Comment by JannisX11** [comment]
Not blocking, but I would recommend including the link to documentation in a clickable way. To do that, you can use the "website" metadata field and you can additionally provide an about text.

**Pull request merged**
