### PR TITLE
Adding Triangle Generator Plugin

### PR DESCRIPTION
**Pull request by DavidEMorales**
Plugin to generate triangles.

Cleaned up my code and updated to the new BlockBench version, sorry it took so long.

### CODE REVIEW

**Comment by DavidEMorales** [comment]
Just realized I didn't pull the most recent plugins.json file, working on it..

**Comment by JannisX11** [comment]
I apologize for the super late response. Could you solve these issues with the plugin?

* Please fix the merge conflicts in the plugins.json file. The entire file is marked as changed, this is potentially caused by tab characters or line ending characters. Indentation must use tab characters as stated in README.md.
* Please choose a slightly more descriptive description. For example, it seems important to me to note that the generated shapes use a staircase effect rather than angled cubes.
* I also found another icon that seems more fitting: `change_history`

Please keep in mind to apply changes both to the plugin source file and the plugins.json file whenever you change the meta data.

**Comment by DoubleF3lix** [comment]
You still have conflicts.

**Comment by DavidEMorales** [comment]
Well, yes, more plugins have been added since I originally posted this code.
I'll leave this branch up for anyone who feels like merging it eventually (it will probably take you all of 10 minutes), but it's clear this is of extremely low priority, and considering I don't use this tool anymore, it will be up to you all to merge it.
I wish you all the best.

**Pull request closed without merging**
