### PR TITLE
Added VoxelShape generator plugin, works for Mojang Mappings and MCP

### PR DESCRIPTION
**Pull request by Spectre0987**
Adds a plugin to export VoxelShapes in Mojang or MCP Mappings

### CODE REVIEW

**Comment by JannisX11** [comment]
The plugin ModUtils already generates VoxelShape, does this offer different functionality?

**Comment by Spectre0987** [comment]
ModUtils doesn't work for Mojang Mappings, and I don't believe it takes into account VoxelShapes modeled in formats with center aligned grids either.

**Comment by Spectre0987** [comment]
Also, it requires you put the model in a folder called VoxelShapes exactly, which is odd to me

**Comment by JannisX11** [comment]
This isn't documented yet I believe, but please add the `"Minecraft: Java Edition"` tag to the plugin meta data. Check the plugin "Fabric Modded Entity" if you need an example.

**Comment by Spectre0987** [comment]
Alright, that's done

**Comment by JannisX11** [comment]
Please mirror your meta data changes to the plugins.json file as well.
See https://github.com/JannisX11/blockbench-plugins#submission

**Comment by Spectre0987** [comment]
Of course, sorry about that

**Pull request merged**
