### PR TITLE
Update csmodel.js

### PR DESCRIPTION
**Pull request by dragonmaster95**
-Imports the UVs in the correct size now instead of basing the UV off of the size of the element.

### CODE REVIEW

**Comment by JannisX11** [comment]
Why does it set the texture size to 16 instead of the size of the texture? That seems counter intuitive for editing

**Comment by dragonmaster95** [comment]
It doesn't set it the texture size to 16, it sets the Project resolution to 16x16.
If it bothers anyone they can set the project resolution to a different value.

**Comment by JannisX11** [comment]
I'd like to set this to the right value by default.

**Comment by dragonmaster95** [comment]
Well "right" value is subjective.
In the model later it won't be 258 to 586 in the uv either.

I did ask Razz, she said both version make sense, and with it being such an easy change for the user I don't think this really matters much.

**Comment by JannisX11** [comment]
Alright, changed it to the native resolution. Looks good?

**Pull request merged**
