### PR TITLE
Fix issue with armor template in Geckolib plugin not exporting parent bone markers

### PR DESCRIPTION
**Pull request by Tslat**
This one fixes an issue where Geckolib locks on boot while trying to find a parent bone but it doesn't exist in a geo armour model because the parent bones weren't exported with the model

I'm not super familiar with the history of this template specifically, so if you know of a reason this shouldn't be done, let me know
As far as I know, these bones are required for export and always have been, something's just been patching them on export to true for some reason

### CODE REVIEW

**Comment by JannisX11** [comment]
Can we get this approved by one of the original creators? @fadookie @bernie-g

**Comment by bernie-g** [comment]
> Can we get this approved by one of the original creators? @fadookie @bernie-g 

Tslat is now the maintainer of geckolib, so any PRs made by him (including this one) have the green flag from me. However this PR needs webpack to be run on the changed code or else it won't do anything.

**Comment by Tslat** [comment]
> > Can we get this approved by one of the original creators? @fadookie @bernie-g
> 
> Tslat is now the maintainer of geckolib, so any PRs made by him (including this one) have the green flag from me. However this PR needs webpack to be run on the changed code or else it won't do anything.

^

And I'm currently having issues trying to get npm to build it at all, so hold for a bit until I ping maybe

**Comment by Tslat** [comment]
@JannisX11 
@bernie-g 

Referring to brief discussion with JTK here:
https://discord.com/channels/314078526104141834/1140141342723420180/1140141342723420180

This should now be ok to merge?

**Comment by bernie-g** [comment]
@JannisX11 Can we get this merged? It's causing a lot of issues for people right now

**Comment by Tslat** [comment]
Done

I'd just left it as npm build applied it since that's the standard format for it, but I've now just replaced it with the current repo's plugin json with animation utils swapped in with the updated version

**Pull request merged**
