### PR TITLE
adding better "Resourcepack Creator"

### PR DESCRIPTION
**Pull request by leopoldhub**
better ressourcepack creator with fully customizable settings
image

### CODE REVIEW

**Comment by JannisX11** [comment]
Sorry for the delay. Two things need changing:

- Fix the plugins.json file. Avoid trailing commas and use consistent indentation, as outlined in README.md
- Please add to the description that this plugin is for Minecraft: Java Edition. Not all users have this context.

**Comment by leopoldhub** [comment]
Hi, I think i fixed all of the issues (the plugins.json, tab indents and precising java edition)

**Comment by DoubleF3lix** [comment]
You have merge conflicts just so you know

**Comment by leopoldhub** [comment]
conflicts fixed

**Comment by JannisX11** [comment]
Please make sure the plugin meets all the requirements as outlined in https://github.com/JannisX11/blockbench-plugins#submission, namely the Minecraft: Java Edition tag, the requirement to sync the plugins.json meta data with the plugin internal meta data, and the source requirement.
Also, the exported JSON models appear to be formatted inefficiently and unlike Blockbench would format them. You can fix this by using `autoStringify` rather than `JSON.stringify`.

**Comment by JannisX11** [comment]
I would love to see this completed one day by the way. The plugin meta-data still does not match between the plugin file and plugins.json and the source files are missing.

**Pull request closed without merging**
