### PR TITLE
Texture stitcher: rewrite box packing and fix different resolution stitching

### PR DESCRIPTION
**Pull request by mchorse**

### CODE REVIEW

**Comment by mchorse** [comment]
Oh... I didn't realize that the new commit will be added to this PR. I hope it's not a big deal that two plugin updates are in a single PR?

**Comment by JannisX11** [comment]
Yeah, please only update one plugin per PR. You can create different PRs on the same repository by using different branches.

**Comment by mchorse** [comment]
> Yeah, please only update one plugin per PR. You can create different PRs on the same repository by using different branches.

I fixed it.

**Comment by JannisX11** [comment]
Is it intentional that box UV support was removed?

**Comment by mchorse** [comment]
> Is it intentional that box UV support was removed?

It appears not, I guess I removed it during implementation and forgot to reimplement it once I got per-face working. 😅

**Comment by JannisX11** [comment]
Per-element box UV is not working. Might not have worked before either.

**Comment by mchorse** [comment]
> Per-element box UV is not working. Might not have worked before either.

I wasn't aware of its existence. I'll try making it work.

**Pull request merged**
