### PR TITLE
Adding animator.js plugin

### PR DESCRIPTION
**Pull request by Command-Master**

### CODE REVIEW

**Comment by JannisX11** [comment]
Please make the description a bit more descriptive, explain which format/edition this is for and how the animations are done. Write an about section explaining how to use the plugin. Update the plugin name to clearly indicate what format this is for.

**Comment by Command-Master** [comment]
Done.

**Comment by Command-Master** [comment]
my description is too big, what may I do?

**Comment by JannisX11** [comment]
Use the "about" section for your instructions.

**Comment by Command-Master** [comment]
OK

**Comment by JannisX11** [comment]
The plugin metadata has not been updated in `plugins.json` yet.

**Comment by Command-Master** [comment]
OK. Just a random question, why metadata needs to be repeated in the `plugins.json` file? Is this for the preview in available?

**Comment by JannisX11** [comment]
> OK. Just a random question, why metadata needs to be repeated in the `plugins.json` file? Is this for the preview in available?

Metadata is required in the plugins.json file for preview when you haven't downloaded the plugin. It is also required in the plugin file itself for when the plugin is loaded locally or for when you don't have an internet connection and the plugins.json file cannot be accessed.

**Comment by JannisX11** [comment]
Please add the "about" section as well.

**Comment by Command-Master** [comment]
Done.

**Pull request merged**
