### PR TITLE
Fixed animation_to_java.js outputting keyframes out of order

### PR DESCRIPTION
**Pull request by VincentHuto**
As the title states Ive since created a fixed version  that simply sorts the keyframes before they are formatted, which seems to work fine not super efficient but it seems to work. If anyone has other ideas Im more than happy to hear them!

Before:
https://streamable.com/hpc7s9
After:
https://streamable.com/fbmp4a

### CODE REVIEW

**Comment by JannisX11** [comment]
When changing the plugin meta data in the plugin file, make sure to also change it in plugins.json.

**Comment by VincentHuto** [comment]
> When changing the plugin meta data in the plugin file, make sure to also change it in plugins.json.

Thanks, Just updated

**Comment by JannisX11** [comment]
Cool!
@MatthewGreenspun permission to merge into your plugin?

**Comment by MatthewGreenspun** [comment]
Yes, fine with me. Thanks @VincentHuto for fixing the issue.

**Comment by VincentHuto** [comment]
Glad to help!

**Pull request merged**
