### PR TITLE
Created a new plugin, "threecore exporter"

### PR DESCRIPTION
**Pull request by Spyeedy**
The plugin is for "Modded Entity" mode. It exports the model to a json format readable for the [ThreeCore mod](https://www.curseforge.com/minecraft/mc-mods/threecore).

**Summary of the plugin's relation to the ThreeCore mod**
Players are able to create their own "addonpacks" for the ThreeCore mod, allowing them to add in armor items and others within ThreeCore's ability.
Models exported by this plugin can be used in their "addonpacks" for custom armor models, to name a use of it.

### CODE REVIEW

**Comment by JannisX11** [comment]
Please make sure that the plugins.json uses valid JSON.

**Comment by Spyeedy** [comment]
Oh! My bad, I'll fix that

**Comment by Spyeedy** [comment]
Uh, fixed json error, tho not too sure what's with the failing check, i've made sure the `plugins.json` is valid

**Comment by JannisX11** [comment]
Don't worry about the automatic checks, I'm just setting it up.

**Pull request merged**
